# Generated by Django 5.1.11 on 2025-07-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_embed_link',
            new_name='embed_url',
        ),
    ]
