# Generated by Django 5.1.11 on 2025-07-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_youtube_embed_link_video_embed_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name='Visto por última vez')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido al historial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Registro de Historial',
                'verbose_name_plural': 'Registros de Historial',
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
